name: tiktok_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  intl: ^0.17.0
  video_player: ^2.6.1
  visibility_detector: ^0.4.0+2
  google_fonts: ^4.0.3
  go_router: ^6.5.6
  camera: ^0.10.4
  permission_handler: ^10.2.0
  gallery_saver: ^2.3.2
  image_picker: ^0.8.7+3
  provider: ^6.0.5
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
flutter_intl:
  enabled: true
