// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIXYXUV65ADN7FOVidUGaRprAxQAH-v1I',
    appId: '1:574678010329:web:55336eb870089e587871c8',
    messagingSenderId: '574678010329',
    projectId: 'flutter-practice-e2045',
    authDomain: 'flutter-practice-e2045.firebaseapp.com',
    databaseURL: 'https://flutter-practice-e2045-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practice-e2045.appspot.com',
    measurementId: 'G-YH14RX9XPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv9C2loIadZBfhkllReF2bIWuCaZtWoBI',
    appId: '1:574678010329:android:5023110350ba2ad37871c8',
    messagingSenderId: '574678010329',
    projectId: 'flutter-practice-e2045',
    databaseURL: 'https://flutter-practice-e2045-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practice-e2045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnp7N6TgOOt7RTgcZON6TLcJB49PmCKUw',
    appId: '1:574678010329:ios:b351da1e865d4a3d7871c8',
    messagingSenderId: '574678010329',
    projectId: 'flutter-practice-e2045',
    databaseURL: 'https://flutter-practice-e2045-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practice-e2045.appspot.com',
    androidClientId: '574678010329-6o804l3jopiri45v52no0u85nt5uje74.apps.googleusercontent.com',
    iosClientId: '574678010329-1fm1ofsmr22i5kle8ph6mt1p3bnp108k.apps.googleusercontent.com',
    iosBundleId: 'com.ujinbak.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnp7N6TgOOt7RTgcZON6TLcJB49PmCKUw',
    appId: '1:574678010329:ios:b2c1dcefedfa8d097871c8',
    messagingSenderId: '574678010329',
    projectId: 'flutter-practice-e2045',
    databaseURL: 'https://flutter-practice-e2045-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practice-e2045.appspot.com',
    androidClientId: '574678010329-6o804l3jopiri45v52no0u85nt5uje74.apps.googleusercontent.com',
    iosClientId: '574678010329-2eehal4hrufp0rjkarqs6ubv3hhko03p.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
